import dayjs, { Dayjs } from 'dayjs';

export interface Application {
    id: string;
    email: string;
    password?: string;
    government: string | null;
    governmentName: string | null;
    name: string;
    surname: string;
    phoneNumber: string;
    createdAt: Dayjs;
    status: RequestStatus;
    adminComment: string | null;
}

export enum RequestStatus {
    PENDING = 'В ожидании',
    APPROVED = 'Одобрено',
    REJECTED = 'Отклонено'
}

export const applications: Application[] = [
    {
        id: '101',
        email: 'ivan.ivanov@mail.com',
        government: 'Финансовый отдел',
        governmentName: 'Центральный офис',
        name: 'Иван',
        surname: 'Иванов',
        phoneNumber: '+7 900 123 45 67',
        createdAt: dayjs().subtract(2, 'day'),
        status: RequestStatus.PENDING,
        adminComment: null,
    },
    {
        id: '102',
        email: 'petr.petrov@mail.com',
        government: 'Отдел кадров',
        governmentName: 'Филиал Москва',
        name: 'Пётр',
        surname: 'Петров',
        phoneNumber: '+7 901 234 56 78',
        createdAt: dayjs().subtract(5, 'day'),
        status: RequestStatus.APPROVED,
        adminComment: 'Документы проверены',
    },
    {
        id: '103',
        email: 'sergey.sergeev@mail.com',
        government: 'Юридический отдел',
        governmentName: null,
        name: 'Сергей',
        surname: 'Сергеев',
        phoneNumber: '+7 902 345 67 89',
        createdAt: dayjs().subtract(1, 'week'),
        status: RequestStatus.REJECTED,
        adminComment: 'Ошибка в данных',
    },
    {
        id: '104',
        email: 'anna.smirnova@mail.com',
        government: 'Маркетинг',
        governmentName: 'Филиал Санкт-Петербург',
        name: 'Анна',
        surname: 'Смирнова',
        phoneNumber: '+7 903 456 78 90',
        createdAt: dayjs().subtract(3, 'day'),
        status: RequestStatus.PENDING,
        adminComment: null,
    },
    {
        id: '105',
        email: 'dmitry.kozlov@mail.com',
        government: 'ИТ-отдел',
        governmentName: 'Хед-офис',
        name: 'Дмитрий',
        surname: 'Козлов',
        phoneNumber: '+7 904 567 89 01',
        createdAt: dayjs().subtract(10, 'day'),
        status: RequestStatus.APPROVED,
        adminComment: 'Все ок',
    },
    {
        id: '106',
        email: 'elena.orlova@mail.com',
        government: 'Служба поддержки',
        governmentName: 'Филиал Казань',
        name: 'Елена',
        surname: 'Орлова',
        phoneNumber: '+7 905 678 90 12',
        createdAt: dayjs().subtract(7, 'day'),
        status: RequestStatus.REJECTED,
        adminComment: 'Недостаточно опыта',
    },
    {
        id: '107',
        email: 'alexey.ivanov@mail.com',
        government: 'Отдел продаж',
        governmentName: 'Филиал Новосибирск',
        name: 'Алексей',
        surname: 'Иванов',
        phoneNumber: '+7 906 789 01 23',
        createdAt: dayjs().subtract(12, 'day'),
        status: RequestStatus.PENDING,
        adminComment: null,
    },
    {
        id: '108',
        email: 'olga.denisova@mail.com',
        government: 'Маркетинг',
        governmentName: 'Филиал Екатеринбург',
        name: 'Ольга',
        surname: 'Денисова',
        phoneNumber: '+7 907 890 12 34',
        createdAt: dayjs().subtract(15, 'day'),
        status: RequestStatus.APPROVED,
        adminComment: 'Заявка принята',
    },
    {
        id: '109',
        email: 'mikhail.sokolov@mail.com',
        government: 'Юридический отдел',
        governmentName: null,
        name: 'Михаил',
        surname: 'Соколов',
        phoneNumber: '+7 908 901 23 45',
        createdAt: dayjs().subtract(1, 'month'),
        status: RequestStatus.REJECTED,
        adminComment: 'Не соответствует требованиям',
    },
    {
        id: '110',
        email: 'nina.petukhova@mail.com',
        government: 'Финансовый отдел',
        governmentName: 'Филиал Казань',
        name: 'Нина',
        surname: 'Петухова',
        phoneNumber: '+7 909 012 34 56',
        createdAt: dayjs().subtract(2, 'week'),
        status: RequestStatus.PENDING,
        adminComment: null,
    },
    {
        id: '111',
        email: 'vladimir.kuznetsov@mail.com',
        government: 'Отдел кадров',
        governmentName: 'Филиал Ростов',
        name: 'Владимир',
        surname: 'Кузнецов',
        phoneNumber: '+7 910 123 45 67',
        createdAt: dayjs().subtract(3, 'week'),
        status: RequestStatus.APPROVED,
        adminComment: 'Принят по всем критериям',
    },
    {
        id: '112',
        email: 'yulia.morozova@mail.com',
        government: 'Служба поддержки',
        governmentName: 'Филиал Москва',
        name: 'Юлия',
        surname: 'Морозова',
        phoneNumber: '+7 911 234 56 78',
        createdAt: dayjs().subtract(2, 'day'),
        status: RequestStatus.REJECTED,
        adminComment: 'Нет опыта работы в данной сфере',
    },
    {
        id: '113',
        email: 'konstantin.makarov@mail.com',
        government: 'ИТ-отдел',
        governmentName: 'Хед-офис',
        name: 'Константин',
        surname: 'Макаров',
        phoneNumber: '+7 912 345 67 89',
        createdAt: dayjs().subtract(4, 'day'),
        status: RequestStatus.PENDING,
        adminComment: null,
    },
    {
        id: '114',
        email: 'ekaterina.melikhova@mail.com',
        government: 'Отдел маркетинга',
        governmentName: 'Филиал Казань',
        name: 'Екатерина',
        surname: 'Мелихова',
        phoneNumber: '+7 913 456 78 90',
        createdAt: dayjs().subtract(6, 'day'),
        status: RequestStatus.APPROVED,
        adminComment: 'Проверено, документы в порядке',
    },
    {
        id: '115',
        email: 'maxim.zhukov@mail.com',
        government: 'Юридический отдел',
        governmentName: 'Филиал Новосибирск',
        name: 'Максим',
        surname: 'Жуков',
        phoneNumber: '+7 914 567 89 01',
        createdAt: dayjs().subtract(8, 'day'),
        status: RequestStatus.REJECTED,
        adminComment: 'Неверные контактные данные',
    },
    {
        id: '116',
        email: 'daria.boriskova@mail.com',
        government: 'Отдел продаж',
        governmentName: 'Филиал Челябинск',
        name: 'Дарья',
        surname: 'Борискова',
        phoneNumber: '+7 915 678 90 12',
        createdAt: dayjs().subtract(9, 'day'),
        status: RequestStatus.PENDING,
        adminComment: null,
    },
    {
        id: '117',
        email: 'oleg.korolev@mail.com',
        government: 'Маркетинг',
        governmentName: 'Филиал Уфа',
        name: 'Олег',
        surname: 'Королев',
        phoneNumber: '+7 916 789 01 23',
        createdAt: dayjs().subtract(13, 'day'),
        status: RequestStatus.APPROVED,
        adminComment: 'Документы подтверждены',
    },
    {
        id: '118',
        email: 'evgeniya.sitnova@mail.com',
        government: 'ИТ-отдел',
        governmentName: 'Филиал Казань',
        name: 'Евгения',
        surname: 'Ситнова',
        phoneNumber: '+7 917 890 12 34',
        createdAt: dayjs().subtract(18, 'day'),
        status: RequestStatus.REJECTED,
        adminComment: 'Нет навыков работы с техникой',
    },
    {
        id: '119',
        email: 'viktor.morozov@mail.com',
        government: 'Отдел продаж',
        governmentName: 'Филиал Самара',
        name: 'Виктор',
        surname: 'Морозов',
        phoneNumber: '+7 918 901 23 45',
        createdAt: dayjs().subtract(1, 'month'),
        status: RequestStatus.PENDING,
        adminComment: null,
    },
    {
        id: '120',
        email: 'irina.korzhova@mail.com',
        government: 'Служба поддержки',
        governmentName: 'Филиал Краснодар',
        name: 'Ирина',
        surname: 'Коржова',
        phoneNumber: '+7 919 012 34 56',
        createdAt: dayjs().subtract(11, 'day'),
        status: RequestStatus.APPROVED,
        adminComment: 'Заявка принята',
    },
];

